apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  labels:
    app: shipping-service
    project: improve-service
spec:
  replicas: 
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: komodor-oomkilled
        image: polinux/stress
        imagePullPolicy: Never
        securityContext{}
        command: ["/bin/sh", "-c"]
        args: ["echo 'Going to allocate 100MB of memory!'; stress --vm 1 --vm-bytes 30M --vm-hang 120 --backoff 10000000 --verbose"]
              - ls
              - /tmp
          initialDelaySeconds: 5
          periodSeconds: 5
